language: ruby
rvm:
  - 2.3.3
services:
  - postgresql
  - redis-server
script: "bundle exec rake"
gemfile:
  - Gemfile
before_script:
  - psql -c 'create database infractores_test;' -U postgres
  - cp config/database.yml.sample config/database.yml
before_install:
  - gem update bundler
